host: http://localhost:9200
index_base_name: harmony
languages:
  - en
  - fr

immutable:
  shards: 1
  replicas: 0

mutable:
  boost_title: 2.0
  boost_content: 1.0
  min_results_before_fallback: 5
  language_detection_confidence_threshold: 0.7
